# Encoding For Nominal Data

In [1]:
import pandas as pd

In [6]:
df = pd.DataFrame({"Name":["wscube","cow","cat","dog","black"]})
df

     Name
0  wscube
1     cow
2     cat
3     dog
4   black

In [7]:
from sklearn.preprocessing import LabelEncoder

In [9]:
le = LabelEncoder()
df["en_name"]=le.fit_transform(df["Name"])

In [10]:
df

     Name  en_name
0  wscube        4
1     cow        2
2     cat        1
3     dog        3
4   black        0

In [11]:
dataset = pd.read_csv("loan.csv")
dataset.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [14]:
la = LabelEncoder()
la.fit(dataset["Property_Area"])

LabelEncoder()

In [16]:
dataset["Property_Area"] = la.fit_transform(dataset["Property_Area"])

In [17]:
dataset

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,2,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,0,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,2,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,2,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,2,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,0,Y
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,0,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,2,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,2,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,1,N

# Encoding For Ordinal Data

In [18]:
df = pd.DataFrame({"Size":['s','m','l','xl','s','m','l','s','s','l','xl',"m"]})

In [20]:
df.head()

  Size
0    s
1    m
2    l
3   xl
4    s

In [23]:
ord_data = [["s","m","l","xl"]]

In [24]:
from sklearn.preprocessing import OrdinalEncoder

In [ ]:
oe = OrdinalEncoder(categories=ord_data)
oe.fit(df[["Size"]])

In [32]:
df["size_en"]=oe.transform(df[["Size"]])

df

Using Map Function

In [43]:
ord_data1 = {"s":0,"m":1,"l":2,"xl":3}

In [44]:
df["size_en_map"]=df["Size"].map(ord_data1)

In [46]:
df

   Size   oe  size_en  size_en_map
0     s  0.0      0.0            0
1     m  1.0      1.0            1
2     l  2.0      2.0            2
3    xl  3.0      3.0            3
4     s  0.0      0.0            0
5     m  1.0      1.0            1
6     l  2.0      2.0            2
7     s  0.0      0.0            0
8     s  0.0      0.0            0
9     l  2.0      2.0            2
10   xl  3.0      3.0            3
11    m  1.0      1.0            1

Perform On Real Dataset

In [47]:
dataset = pd.read_csv("loan.csv")

In [48]:
dataset.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [49]:
dataset["Property_Area"].unique()

array(['Urban', 'Rural', 'Semiurban'], dtype=object)

In [50]:
dataset["Property_Area"].fillna(dataset["Property_Area"].mode()[0],inplace=True)

In [51]:
en_data_ord = [['Rural', 'Semiurban','Urban']]

In [52]:
from sklearn.preprocessing import OrdinalEncoder

In [58]:
oen = OrdinalEncoder(categories=en_data_ord)

In [61]:
dataset["Property_Area"]=oen.fit_transform(dataset[["Property_Area"]])

In [62]:
dataset

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,2.0,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,0.0,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,2.0,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,2.0,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,2.0,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,0.0,Y
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,0.0,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,2.0,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,2.0,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,1.0,N