In [1]:
import pandas as pd

In [2]:
dataset = pd.read_csv("Social_Network_Ads.csv")

In [3]:
dataset.head()

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [4]:
dataset.drop(columns=["User ID","Gender"],inplace=True)

In [5]:
dataset["Purchased"].value_counts()

Purchased
0    257
1    143
Name: count, dtype: int64

In [8]:
x = dataset.iloc[:,:-1]
y = dataset['Purchased']

In [6]:
from imblearn.under_sampling import RandomUnderSampler

In [11]:
ru = RandomUnderSampler()
ru_x , ru_y = ru.fit_resample(x,y)

In [12]:
ru_x

     Age  EstimatedSalary
110   39            71000
193   19            70000
35    35            27000
49    31            89000
196   30            79000
..   ...              ...
393   60            42000
395   46            41000
396   51            23000
397   50            20000
399   49            36000

[286 rows x 2 columns]

In [14]:
ru_y.value_counts()

Purchased
0    143
1    143
Name: count, dtype: int64